
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: my_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
  

    depends_on:
      - postgres

  ngrok:
    image: ngrok/ngrok:latest
    container_name: my_ngrok
    command: http django:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - django
    ports:
      - "4040:4040"

volumes:
  postgres_data:
